name: Test
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install uv
      run: python -m pip install uv

    - name: Create virtual environment
      run: uv venv .venv

    - name: Activate virtual environment
      run: source .venv/Scripts/activate

    - name: Install dependencies
      run: uv pip install -r requirements.txt

    - name: Run main.py
      run: python main.py
