name: Test
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Install python
      run: uv python install

    - name: Create virtual environment
      run: uv venv .venv

    - name: Activate virtual environment
      run: .venv/Scripts/activate

    - name: Install dependencies
      run: uv pip install -r requirements.txt

    - name: Run main.py
      shell: bash
      run: strace python main.py
